Feature/hir 30 merge accommodations data from different suppliers
happy-travel/nakijin pull request #2
Opened 2020-10-16 11:40 UTC by hasmikharutyunyan

Separate PR will be for update EdoContracts.

2020-10-16 15:27 UTC, kirillta requested changes

2020-10-16 15:27 UTC, kirillta commented on HappyTravel.PropertyManagement.Data/Models/StaticData.cs
> +    public class StaticData
What this class do?

2020-10-16 15:27 UTC, kirillta commented on HappyTravel.PropertyManagement.Data/Models/StaticDataTypes.cs
> +    public enum StaticDataTypes
Shady naming

2020-10-16 15:27 UTC, kirillta commented on HappyTravel.PropertyManagement.Data/Models/Accommodations/WideAccommodationDetails.cs
> +    public class WideAccommodationDetails
On my opinion `wide` relates to geography, I suggest `rich` here.

2020-10-16 15:27 UTC, kirillta commented on HappyTravel.PropertyManagement.Data/Models/Accommodations/WideAccommodationDetails.cs
> +    public class WideAccommodationDetails
Or to divide settings and the content by two tables

2020-10-16 15:27 UTC, kirillta commented on HappyTravel.PropertyManagement.Data/Models/Accommodations/AccommodationDataTypes.cs
> +    public enum AccommodationDataTypes
`AccommodationMatchParameters` maybe?

2020-10-16 15:27 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +        private SlimLocationInfo MergeLocationInfo(in List<Suppliers> suppliersPriority,
`in List` and `in Dictionary` have no sense, looks like a copy-paste issue

2020-10-16 15:27 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +
Formatting!

2020-10-19 08:01 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Data/Models/StaticData.cs
> +    public class StaticData
We had decided in `edo` this kind of data save in one table. I think here also maybe we can have other static datas.

2020-10-19 08:06 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Data/Models/StaticDataTypes.cs
> +    public enum StaticDataTypes
What are you suggest for that? I have used edo naming.

2020-10-19 08:07 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Data/Models/Accommodations/WideAccommodationDetails.cs
> +    public class WideAccommodationDetails
I thought  about that, but maybe in next PR I will do that

2020-10-19 08:10 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Data/Models/Accommodations/AccommodationDataTypes.cs
> +    public enum AccommodationDataTypes
I think `MatchParameters` will not understandable. This enum for indicating data type in accommodation, maybe we will use it not only for match.

2020-10-19 08:14 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +        private SlimLocationInfo MergeLocationInfo(in List<Suppliers> suppliersPriority,
I think `in` have sense everywhere ( on reference types also : to not copy reference).
But I can remove fo understandability.

2020-10-19 08:41 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Services/Mappers/AccommodationMapper.cs
> +                    tree.Insert(new Point(ac.Value.Location.Coordinates.Longitude,
Where I can see that?

2020-10-19 08:45 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +            if (accommodation.IsCalculated)
I think failure, because we call calculate and we must be informed that data already calculated, and we can not calculate.

2020-10-19 11:46 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Services/Mappers/AccommodationMapper.cs
> +                    tree.Insert(new Point(ac.Value.Location.Coordinates.Longitude,
We have only the opposite one, but you may add that [here](https://github.com/happy-travel/geography/blob/df04d543312bdf0828c6ce2b8eafa1debd0ea662/HappyTravel.Geography/GeoPoint.cs#L20)

2020-10-19 12:14 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Services/Mappers/AccommodationMapper.cs
> +                    tree.Insert(new Point(ac.Value.Location.Coordinates.Longitude,
Here is only call of constructor, are you think for that we need a method?

2020-10-19 12:19 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +        private SlimLocationInfo MergeLocationInfo(in List<Suppliers> suppliersPriority,
To copy or not to copy a reference is similar by effort. If you want to show a read-only nature of the parameter, it has no point in case of a list, because its members are still modifiable

2020-10-19 12:23 UTC, kirillta commented on HappyTravel.PropertyManagement.Data/Models/StaticDataTypes.cs
> +    public enum StaticDataTypes
Ok

2020-10-19 12:24 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +            if (accommodation.IsCalculated)
I think the state may change in background or something. Let's see other opinions
@oleg1std @mingazhev

2020-10-19 12:26 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +        private SlimLocationInfo MergeLocationInfo(in List<Suppliers> suppliersPriority,
Yes, shure. I have removed that to not have an confusion.

2020-10-19 12:31 UTC, kirillta commented on HappyTravel.PropertyManagement.Data/Models/Accommodations/AccommodationDataTypes.cs
> +    public enum AccommodationDataTypes
Then `AccommodationPropertyTypes`? I don't like ambiguous of the word "Property" in this context
@oleg1std @mingazhev

2020-10-19 20:38 UTC, kirillta approved these changes
Approved, but those two issues when we wait for @mingazhev or @oleg1std

2020-10-20 13:13 UTC, merged