NAKIJIN-208. Add LocalityCandidatesCollector service
happy-travel/nakijin pull request #211
Opened 2021-11-12 13:38 UTC by oleg1std

Add LocalityCandidatesCollector service

2021-11-12 14:30 UTC, hasmikharutyunyan requested changes

2021-11-12 14:30 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                    .Where(l => l.Country.Code == countryCode)
I think `IsActive` filter also needed

2021-11-12 14:30 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            List<MultiLanguage<string>> NormalizeLocalityNames(string countryName, List<MultiLanguage<string>> localityNames)
I thin we have these methods in another place in we can use them

2021-11-12 14:30 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                var normalizedLocalityNames = NormalizeLocalityNames(countryName, rawLocalityNames);
I think here needed `Distinct`, after normalization can be duplicates.

2021-11-12 14:30 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                _context.UpdateRange(localityCandidates);
maybe AddRange() ?

2021-11-12 15:15 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            List<MultiLanguage<string>> NormalizeLocalityNames(string countryName, List<MultiLanguage<string>> localityNames)
what place?

2021-11-12 15:17 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                    .Where(l => l.Country.Code == countryCode)
Why? We have to compare all localities

2021-11-12 15:21 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                var normalizedLocalityNames = NormalizeLocalityNames(countryName, rawLocalityNames);
NormalizeLocalityNames method returns normalized unique items

2021-11-12 15:21 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                _context.UpdateRange(localityCandidates);
fixed

2021-11-12 15:30 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            List<MultiLanguage<string>> NormalizeLocalityNames(string countryName, List<MultiLanguage<string>> localityNames)
This method filters localities, groups by name, and returns unique localities with the largest number of languages.

2021-11-12 15:31 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            List<MultiLanguage<string>> NormalizeLocalityNames(string countryName, List<MultiLanguage<string>> localityNames)
renamed

2021-11-12 15:39 UTC, AlexeyShok approved these changes

2021-11-15 08:20 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            List<MultiLanguage<string>> NormalizeLocalityNames(string countryName, List<MultiLanguage<string>> localityNames)
In `MultilingualDataHelper` exists methods for normalization, I think You can use them

2021-11-15 08:21 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                    .Where(l => l.Country.Code == countryCode)
If we will compare all, we can miss locality that in inActive status, and will not add then

2021-11-15 08:23 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            List<MultiLanguage<string>> NormalizeLocalityNames(string countryName, List<MultiLanguage<string>> localityNames)
in 'MultilingualDataHelper' we have methods for normalization, I think You can use them.

2021-11-16 14:47 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            List<MultiLanguage<string>> NormalizeLocalityNames(string countryName, List<MultiLanguage<string>> localityNames)
service has been re-implemented

2021-11-17 11:50 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +        private async Task<Dictionary<Suppliers, DateTime>> GetSuppliersDownloadFromDate(List<Suppliers> suppliers, LocalityCollectorModes mode, CancellationToken cancellationToken)
`LastCollectionDate` ?

2021-11-17 11:50 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +        private async Task CollectEnglishLocalitiesForSupplier(Suppliers supplier, DateTime fromDate, List<MultiLanguage<string>> rawLocalityCandidateNames,
maybe instead of word `English` better to use `Default` ?

2021-11-17 11:50 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            var localityCandidatesEnName = localityCandidates.Select(lc => lc.En);
I think here als needed Distinct

2021-11-17 11:50 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                .Distinct()
I think needed distinct only by English name

2021-11-17 11:50 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                .Select(l => new MultiLanguage<string> { En = l.En })
am I correct, that we are missing other language names?

2021-11-17 12:27 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Options/LocalityCollectorModes.cs
> +    public enum LocalityCollectorModes
Enum called by analogy with MappingModes

2021-11-17 12:28 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +        private async Task<Dictionary<Suppliers, DateTime>> GetSuppliersDownloadFromDate(List<Suppliers> suppliers, LocalityCollectorModes mode, CancellationToken cancellationToken)
renamed

2021-11-17 12:38 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +        private async Task CollectEnglishLocalitiesForSupplier(Suppliers supplier, DateTime fromDate, List<MultiLanguage<string>> rawLocalityCandidateNames,
renamed

2021-11-17 13:41 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +        private async Task<Dictionary<Suppliers, DateTime>> GetSuppliersDownloadFromDate(List<Suppliers> suppliers, LocalityCollectorModes mode, CancellationToken cancellationToken)
modified

2021-11-17 13:41 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +        private async Task CollectEnglishLocalitiesForSupplier(Suppliers supplier, DateTime fromDate, List<MultiLanguage<string>> rawLocalityCandidateNames,
fixed

2021-11-17 13:41 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                .Distinct()
localityCandidates are unique by En language at that point

2021-11-17 13:42 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Options/LocalityCollectorModes.cs
> +    public enum LocalityCollectorModes
Yes `MappingMode`, not a `MapperMode`.

2021-11-17 13:55 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +                .Select(l => new MultiLanguage<string> { En = l.En })
fixed

2021-11-17 14:19 UTC, hasmikharutyunyan approved these changes

2021-11-17 15:31 UTC, oleg1std commented on HappyTravel.Nakijin.Updater/Workers/Localities/LocalityCandidatesCollector.cs
> +            var localityCandidatesEnName = localityCandidates.Select(lc => lc.En);
items are unique at that point of execution

2021-11-17 15:31 UTC, merged