Technical/aa 1101 accommodation mapper refactoring
happy-travel/nakijin pull request #256
Opened 2022-02-01 09:50 UTC by hasmikharutyunyan

2022-02-01 14:55 UTC, kirillta commented on HappyTravel.Nakijin.Updater/Infrastructure/ServiceCollectionExtensions.cs
> +                 o.Mode = string.IsNullOrWhiteSpace(mappingMode)
An extra space here

2022-02-01 14:55 UTC, kirillta commented on HappyTravel.Nakijin.Updater/Infrastructure/ServiceCollectionExtensions.cs
> +                 o.WorkersToRun = string.IsNullOrWhiteSpace(workersToRun)
An extra space here

2022-02-01 14:55 UTC, kirillta commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationValidator.cs
> +        if (!accommodation.IsActive)
Shouldn't this one be the first?

2022-02-01 14:55 UTC, kirillta commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationDataStorageBySupplierAndCountry.cs
> +
Do we need empty lines here?

2022-02-01 14:55 UTC, kirillta commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationsBatchChangeCollector.cs
> +                     out var existingNotActive))
Hmm

2022-02-02 11:28 UTC, AlexeyShok requested changes

2022-02-02 11:28 UTC, AlexeyShok commented on HappyTravel.Nakijin.Data/Migrations/20220128125135_ChangeDeactivationReasonToNewValues.cs
> +            SET ""DeactivationReason"" = 7
DeactivationReason can't be 7

2022-02-02 18:47 UTC, oleg-n-k commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationDataStorageBySupplierAndCountry.cs
> +    public async Task Initialize(Suppliers supplier, string countryCode, CancellationToken cancellationToken)
cancellation token isn't used below

2022-02-02 18:49 UTC, oleg-n-k commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationDataStorageBySupplierAndCountry.cs
> +        => NotSupplierAccommodationsTree = await _accommodationMapperDataRetrieveService.GetCountryAccommodationsTree(countryCode, supplier);
Cancellation token can be used here

2022-02-02 18:51 UTC, oleg-n-k commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationDataStorageBySupplierAndCountry.cs
> +        var accommodationsOfSupplier = await _accommodationMapperDataRetrieveService.GeCountryAccommodationBySupplier(countryCode, supplier);
Ge**t**CountryAccommodationBySupplier
Cancellation token can be used here

2022-02-02 18:53 UTC, oleg-n-k commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationDataStorageBySupplierAndCountry.cs
> +
extra line

2022-02-03 06:25 UTC, AlexeyShok approved these changes

2022-02-06 16:38 UTC, oleg-n-k approved these changes

2022-02-16 19:28 UTC, kirillta commented on HappyTravel.Nakijin.Api/Services/AdministratorServices/Management/Accommodations/AccommodationDataCorrectionService.cs
> +            .SingleOrDefaultAsync();
Why do you need two exactly similar methods except this very line? You may reuse the second one here

2022-02-16 19:28 UTC, kirillta commented on HappyTravel.Nakijin.Core/Services/MultilingualDataHelper.cs
> +    private bool IsSanitizingNeeded(ContactInfo contactInfo)
Do we need this check if in `Sanitize` method we check it again?

2022-02-17 12:40 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Core/Services/MultilingualDataHelper.cs
> +    private bool IsSanitizingNeeded(ContactInfo contactInfo)
I think it is done for logging error if all contacts of supplier not valid

2022-02-17 12:42 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Api/Services/AdministratorServices/Management/Accommodations/AccommodationDataCorrectionService.cs
> +            .SingleOrDefaultAsync();
the core logic of methods is done in one place, here just the query to the db is different, I think it is ok.

2022-02-24 14:04 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Api/Services/AdministratorServices/Management/Accommodations/AccommodationDataCorrectionService.cs
> +            .SingleOrDefaultAsync();
Changed

2022-02-24 21:58 UTC, kirillta commented on HappyTravel.Nakijin.Data/Extensions/NakijinContextExtensions.cs
> +        var attachedEntities = context.ChangeTracker.Entries()
But its mock could. I speak from experience

2022-02-25 11:05 UTC, oleg-n-k commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationsBatchChangeCollector.cs
> +            ProcessDeactivation(accommodation.SupplierCode, deactivationReason, accommodation);
Just Deactivate maybe?

2022-02-25 11:11 UTC, oleg-n-k commented on HappyTravel.Nakijin.Updater/Workers/AccommodationMapping/AccommodationsBatchChangeCollector.cs
> +            ProcessDeactivation(accommodation.SupplierCode, DeactivationReasons.MatchingWithOther, accommodation);
How about just using the name "Deactivate"?

2022-02-25 11:42 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Data/Extensions/NakijinContextExtensions.cs
> +        var attachedEntities = context.ChangeTracker.Entries()
Done

2022-02-26 10:42 UTC, kirillta approved these changes

2022-02-28 05:59 UTC, merged