Feature/hir 124 api for manual merge accommodations data
happy-travel/nakijin pull request #6
Opened 2020-11-23 13:39 UTC by hasmikharutyunyan

2020-11-23 15:36 UTC, kirillta requested changes

2020-11-23 15:36 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Controllers/AccommodationsController.cs
> +        [HttpPost("accommodations/uncertainMatches/{uncertainMatchId}/match")]
`uncertain-matches` at least, but better `accommodations/matches/{uncertainMatchId}/uncertain`

2020-11-23 15:36 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +            if (!uncertainMatch.IsActive)
Could this be merged with the upper statement? Like 
```csharp
await _context.AccommodationUncertainMatches
    .Where(um => um.IsActive)
    .SingleOrDefaultAsync(um => um.Id == uncertainMatchId);
```

2020-11-23 15:36 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +            _context.Update(firstAccommodation);
Looks like a good place for transaction

2020-11-23 16:30 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +            if (!uncertainMatch.IsActive)
Yes, but  we decided to not throw error in that kind of situations.

2020-11-23 16:31 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +            _context.Update(firstAccommodation);
Yes, `SaveChanges` by default opened an transaction (here is one `Savechanges`)

2020-11-23 16:32 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Controllers/AccommodationsController.cs
> +        [HttpPost("accommodations/uncertainMatches/{uncertainMatchId}/match")]
Here `match` is used as verb, we match that was uncertain matched.

2020-11-24 12:12 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Controllers/AccommodationsController.cs
> +        [HttpPost("accommodations/uncertainMatches/{uncertainMatchId}/match")]
Then `accommodations/{uncertainMatchId}/match-uncertain`?

2020-11-24 12:15 UTC, hasmikharutyunyan commented on HappyTravel.PropertyManagement.Api/Controllers/AccommodationsController.cs
> +        [HttpPost("accommodations/uncertainMatches/{uncertainMatchId}/match")]
I understand what You want, but `uncertainmatchId`  is not an accommodation Id, and here will be not understandable I think

2020-11-24 12:19 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Services/AccommodationService.cs
> +            if (!uncertainMatch.IsActive)
As for me both conditions are safe to return success

2020-11-24 12:25 UTC, kirillta commented on HappyTravel.PropertyManagement.Api/Controllers/AccommodationsController.cs
> +        [HttpPost("accommodations/uncertainMatches/{uncertainMatchId}/match")]
Agree

2020-11-26 11:46 UTC, oleg1std commented on HappyTravel.PropertyManagement.Api/Controllers/AccommodationsController.cs
The controller contains get accommodations methods with incorrect response type in [ProducesResponseType]

2020-11-26 16:28 UTC, oleg1std approved these changes

2020-11-26 22:06 UTC, kirillta approved these changes

2020-11-27 08:48 UTC, merged