If a worker execution is failed the execution of other workers will be skipped
happy-travel/nakijin pull request #662
Opened 2022-10-15 14:20 UTC by oleg-n-k

If a worker execution is failed the execution of other workers will be skipped

2022-10-18 10:56 UTC, hasmikharutyunyan requested changes

2022-10-18 10:56 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Updater/Workers/Auxiliaries/InvalidAccommodationMappingAnalyzer.cs
> +                }catch (TaskCanceledException)
`catch` from new line ?

2022-10-20 05:38 UTC, oleg-n-k commented on HappyTravel.Nakijin.Updater/Workers/AccommodationDataCorrection/AccommodationDataCorrector.cs
> +                    return Result.Success();
fixed

2022-10-20 05:47 UTC, oleg-n-k commented on HappyTravel.Nakijin.Updater/Workers/Auxiliaries/InvalidAccommodationMappingAnalyzer.cs
> +                }catch (TaskCanceledException)
fixed

2022-10-24 12:46 UTC, hasmikharutyunyan approved these changes

2022-10-24 14:44 UTC, merged