feature/PU-137 Predictions update
happy-travel/nakijin pull request #78
Opened 2021-04-18 15:25 UTC by oleg1std

Adds a service to publish predictions to the Redis Stream

2021-04-19 07:54 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Api/Models/PredictionsUpdate/EntryType.cs
> +    public enum EntryTypes
Ass I remember we decided to not name items of enum by verbs
And maybe EventType will be more understandable?

2021-04-19 07:54 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/PredictionsUpdateService.cs
> +        public async Task Publish(List<Location> locations, EntryTypes type, CancellationToken cancellationToken = default)
I think we can have here Publish method with one location

2021-04-19 11:35 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Models/PredictionsUpdate/EntryType.cs
> +    public enum EntryTypes
fixed

2021-04-19 12:59 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/PredictionsUpdateService.cs
> +        public async Task Publish(List<Location> locations, EntryTypes type, CancellationToken cancellationToken = default)
the method has been added

2021-04-19 23:07 UTC, kirillta requested changes

2021-04-20 10:52 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Infrastructure/DefaultSerializer.cs
> +    public class DefaultSerializer: ISerializer
fixed

2021-04-20 11:30 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Infrastructure/PredictionUpdateOptions.cs
> +        public string Stream { get; set; } = string.Empty;
fixed

2021-04-20 11:46 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Infrastructure/PredictionsUpdateExtensions.cs
> +                            Port = 6379
fixed

2021-04-20 11:47 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/PredictionsUpdateService.cs
> +        private readonly string _stream;
fixed

2021-04-20 11:47 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/PredictionsUpdateService.cs
> +        NameValueEntry Build(Location location, EventTypes type)
fixed

2021-04-20 11:48 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/PredictionsUpdateService.cs
> +        private bool InitStream()
InitStreamIfNeeded ?

2021-04-20 11:50 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/PredictionsUpdateService.cs
> +                foreach (var batchOfLocations in ListHelper.Split(locations, batchSize))
fixed

2021-04-20 19:38 UTC, kirillta commented on HappyTravel.Nakijin.Api/Infrastructure/PredictionsUpdateExtensions.cs
> +            var redisOptions = vaultClient.Get(configuration["PredictionsUpdate:Redis"]).GetAwaiter().GetResult();
This one still not fixed

2021-04-20 19:38 UTC, kirillta commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/IPredictionsUpdateService.cs
> +        Task Publish(Location location, EventTypes type);
And this one

2021-04-20 19:38 UTC, kirillta commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/PredictionsUpdateService.cs
> +        private bool InitStream()
Probably, yes

2021-04-20 19:39 UTC, kirillta reviewed
Some issues was missed due other changes

2021-04-22 10:19 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/PredictionsUpdateService.cs
> +        private bool InitStream()
fixed

2021-04-22 10:38 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Models/PredictionsUpdate/EntryType.cs
> +    public enum EventTypes
fixed

2021-04-22 10:39 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Models/PredictionsUpdate/EntryType.cs
> +        Add = 0,
fixed

2021-04-22 10:39 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Infrastructure/PredictionsUpdateExtensions.cs
> +        public static IServiceCollection AddPredictionsUpdate(this IServiceCollection services, IConfiguration configuration, IWebHostEnvironment environment)
fixed

2021-04-22 10:39 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Infrastructure/PredictionsUpdateExtensions.cs
> +            var redisOptions = vaultClient.Get(configuration["PredictionsUpdate:Redis"]).GetAwaiter().GetResult();
fixed

2021-04-22 11:14 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Services/PredictionsUpdate/IPredictionsUpdateService.cs
> +        Task Publish(Location location, EventTypes type);
The service has been renamed

2021-04-22 11:18 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Models/PredictionsUpdate/LocationEntry.cs
> +    public readonly struct LocationEntry
Struct has been renamed

2021-04-22 11:31 UTC, kirillta approved these changes

2021-04-22 12:45 UTC, merged