Technical/refactoring
happy-travel/nakijin pull request #92
Opened 2021-05-13 11:13 UTC by hasmikharutyunyan

2021-05-14 13:01 UTC, mingazhev approved these changes
With comments

2021-05-14 13:01 UTC, mingazhev commented on HappyTravel.Nakijin.Api/Services/Workers/AccommodationsMapping/IAccommodationsMapperDataRetrieveService.cs
> +        Task<DateTime> GetLastMappingDate(Suppliers supplier, CancellationToken cancellationToken);
One line between methods in one case and two lines in another

2021-05-14 21:57 UTC, kirillta commented on HappyTravel.Nakijin.Api/Controllers/AccommodationsManagementController.cs
> +                        var mapper = scope.ServiceProvider.GetRequiredService<IAccommodationsMapper>();
`IAccommodationMapper` is the right name

2021-05-14 21:57 UTC, kirillta commented on HappyTravel.Nakijin.Api/Controllers/LocationsManagementController.cs
> +                        var locationService = scope.ServiceProvider.GetRequiredService<ILocationsMapper>();
And `ILocationMapper` here as well

2021-05-14 21:57 UTC, kirillta commented on HappyTravel.Nakijin.Api/Infrastructure/Logging/LoggerExtensions.g.cs
> +                $"INFORMATION | LocalityZonesMapper: {{message}}");
Additional subject must be in a singular form generally

2021-05-14 21:57 UTC, kirillta commented on HappyTravel.Nakijin.Api/Services/Workers/MultilingualDataHelper.cs
> +            if (name == null)
use `is` whenever possible

2021-05-16 08:27 UTC, oleg1std commented on HappyTravel.Nakijin.Api/Services/Workers/AccommodationsMapping/IAccommodationsMapperDataRetrieveService.cs
> +
extra line

2021-05-18 08:23 UTC, hasmikharutyunyan commented on HappyTravel.Nakijin.Api/Infrastructure/Logging/LoggerExtensions.g.cs
> +                $"INFORMATION | LocalityZonesMapper: {{message}}");
Do You mean  `MappingLocalityZonesOfSpecifiedCountryFinish` name in singular form, or `LocalityZonesMapper` ?

2021-05-23 14:24 UTC, kirillta commented on HappyTravel.Nakijin.Api/Infrastructure/Logging/LoggerExtensions.g.cs
> +                $"INFORMATION | LocalityZonesMapper: {{message}}");
Both

2021-05-23 14:29 UTC, kirillta requested changes
All names must be fixed

2021-05-25 20:10 UTC, kirillta approved these changes

2021-05-26 09:39 UTC, merged